
/*
    w3resource PL/SQL Fundamentals
*/
CREATE TABLE employees2 (
    EMPLOYEE_ID INT NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DECIMAL(8, 2),
    COMMISSION_PCT DECIMAL(2, 2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    PRIMARY KEY (EMPLOYEE_ID)
);

INSERT INTO employees2 (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
SELECT
  ROW_NUMBER() OVER (ORDER BY ROWNUM) + 100 AS EMPLOYEE_ID,
  'FirstName' || ROW_NUMBER() OVER (ORDER BY ROWNUM) AS FIRST_NAME,
  'LastName' || ROW_NUMBER() OVER (ORDER BY ROWNUM) AS LAST_NAME,
  'employee' || ROW_NUMBER() OVER (ORDER BY ROWNUM) || '@example.com' AS EMAIL,
  '555-' || TRUNC(DBMS_RANDOM.VALUE(1, 999)) || '-' || TRUNC(DBMS_RANDOM.VALUE(1, 9999)) AS PHONE_NUMBER,
  DATE '2021-01-01' + TRUNC(DBMS_RANDOM.VALUE(1, 3650)) AS HIRE_DATE,
  CASE
    WHEN TRUNC(DBMS_RANDOM.VALUE(0, 1)) = 0 THEN 'IT_PROG'
    ELSE 'SA_MAN'
  END AS JOB_ID,
  TRUNC(DBMS_RANDOM.VALUE(1, 10000)) * 10 AS SALARY,
  CASE
    WHEN TRUNC(DBMS_RANDOM.VALUE(0, 1)) = 0 THEN NULL
    ELSE TRUNC(DBMS_RANDOM.VALUE(0, 50)) * 0.01
  END AS COMMISSION_PCT,
  CASE
    WHEN TRUNC(DBMS_RANDOM.VALUE(0, 9)) = 0 THEN NULL
    ELSE TRUNC(DBMS_RANDOM.VALUE(1, 100)) + 100
  END AS MANAGER_ID,
  TRUNC(DBMS_RANDOM.VALUE(10, 19)) AS DEPARTMENT_ID
FROM
  DUAL
CONNECT BY
  LEVEL <= 50;
  
select * from employees2;